### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by philpott** [cookiefirst/gtm-template#1]
https://github.com/cookiefirst/gtm-template/blob/9144f76e4bb924c1303808f78826e179b3ba7379/template.tpl#L175

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by cookiefirst** [comment]
Sorry about that.. we pushed an update also to update to our newer embed codes.
